name: build
on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version'
        default: '17'
        required: false
        type: string
jobs:
  build:
    name: build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ inputs.java-version }}
          cache: 'maven'
      - name: Build project
        run: mvn -ntp -B -e clean install