name: Create fix branch
on:
  workflow_call:

jobs:
  fix:
    name: create fix branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_PAT }}
      - name: Config git
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - uses: lorislab/install-samo-action@v1
      - name: Create fix branch
        run: samo project patch --tag ${{ github.ref_name }}
